=== bixash/Academics/dotWeb/dot-xml/dot-class/dtd/salesman/sales.dtd
<!ELEMENT sales (salesman+)>
<!ELEMENT salesman (name, phone, area, records)>
<!ELEMENT name (first, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT area (#PCDATA)>
<!ELEMENT records (record+)>
<!ELEMENT record (product, quantity, price, date)>
<!ELEMENT product (sku, product_name)>
<!ELEMENT sku (#PCDATA)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== bixash/Academics/dotWeb/dot-xml/dot-classwork/dtd/salesman/sales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales SYSTEM "sales.dtd">

<sales>
    <salesman>
        <name>
            <first></first>
            <middle></middle>
            <last></last>
            
        </name>
        <phone></phone>
        <area></area>
        <records>
            <record>
                <product>
                    <sku></sku>
                    <product_name></product_name>
                </product>
                <quantity></quantity>
                <price></price>
                <date></date>
            </record>
            
        </records>
    </salesman>

</sales>
