=== bixash/Academics/dotWeb/dot-xml/xml-projects/xsd-books/books.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="author" type="nameType" maxOccurs="unbounded"></xs:element>
                            <xs:element name="page" type="xs:integer"></xs:element>
                            <xs:element name="price" type="priceTag"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="first" type="xs:string"></xs:element>
            <xs:element name="middle" type="xs:string"></xs:element>
            <xs:element name="last" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="priceTag">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="600"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== bixash/Academics/dotWeb/dot-xml/xml-projects/books/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 4. Write a valid xml to validate following details.
a. Validate record of books with (name, author, pageno, price)
b. Name have first name, middle name and last name.
c. Author can be multiple
d. And highest price limit is 600.
e. Book have isbn as an attribute -->


<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book isbn="12">
        <name></name>
        <author>
            <first></first>
            <middle></middle>
            <last></last>
        </author>
        <author>
            <first></first>
            <middle></middle>
            <last></last>
        </author>
        <page>609</page>
        <price>600</price>
    </book>
</books>
