=== bixash/Academics/dotWeb/dot-xml/xml-projects/songs/songs.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="songs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="song" minOccurs="4" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="singer" type="xs:string"></xs:element>
                            <xs:element name="compose" type="xs:string"></xs:element>
                            <xs:element name="length" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bixash/Academics/dotWeb/dot-xml/xml-projects/songs/songs.xml
<?xml version="1.0" encoding="UTF-8"?>
<songs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="songs.xsd">
    <song>
        <name>hnnh</name>
        <singer>hnffhn</singer>
        <compose>hf</compose>
        <length>hfh</length>
    </song>
    <song>
        <name>hfhf</name>
        <singer></singer>
        <compose></compose>
        <length></length>
    </song>
    <song>
        <name></name>
        <singer></singer>
        <compose></compose>
        <length></length>
    </song>
    <song>
        <name></name>
        <singer></singer>
        <compose></compose>
        <length></length>
    </song>
    <song>
        <name></name>
        <singer></singer>
        <compose></compose>
        <length></length>
    </song>
</songs>
<!-- 3. Write XML code to store at least four songs with details (name, singer,
compose by, length). -->
