=== bixash/Academics/dotWeb/dot-xml/schema-attr/att-book.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="author" type="nameType" maxOccurs="unbounded"></xs:element>
                            <xs:element name="isbn" type="isbnType"></xs:element>
                            <xs:element name="publisher" type="xs:string"></xs:element>
                            <xs:element name="edition" type="xs:integer"></xs:element>
                            <xs:element name="price" type="priceType"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="priceType">
        <xs:simpleContent>
            <xs:extension base="priceTag">
                <xs:attribute name="currency" type="currencyType" default="npr"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:pattern value="npr|usd"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priceTag">

        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="1000"></xs:maxInclusive>
            <xs:minInclusive value="0"></xs:minInclusive>
        </xs:restriction>

    </xs:simpleType>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="first" type="xs:string"></xs:element>
            <xs:element name="middle" type="xs:string"></xs:element>
            <xs:element name="last" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="title" default="ms">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ms" />
                    <xs:enumeration value="mr" />
                    <xs:enumeration value="mrs" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:simpleType name="isbnType">
        <xs:restriction base="xs:string">
            <xs:minLength value="13" />
            <xs:maxLength value="13" />
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

<!-- <xs:complexType name="priceType">
    <xs:simpleContent>
        <xs:extension
base="xs:integer">
            <xs:attribute name="currency" type="xs:string"
default="npr"></xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType> -->

=== bixash/Academics/dotWeb/dot-xml/schema-attr/att-book.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="att-book.xsd">
    <book id="wew">
        <name></name>
        <author title="ms">
            <first></first>
            <middle></middle>
            <last></last>
        </author>

        <isbn>1111111111111</isbn>
        <publisher></publisher>
        <edition>1221</edition>
        
        <price currency="usd">899</price>
    </book>


</books>

<!-- 10.Write XML Schema and prepare file, which will display the Book
information. It includes the following
 Title of the book
 Multiple Author Name with details(first, middle, last) name
 ISBN number (consists of 13 digit)
 Publisher name
 Edition
 Price(price limit is upto 1000
 Book has book id attribute
 Author has title attribute with (mr,ms,mrs) value and default ms
 Price has currency attribute with default value "npr" -->
