=== bixash/Academics/dotWeb/dot-xml/dot-class/schema/phone/phoneNumbers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="phoneNumbers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="entries">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name ="entry" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="first" type="xs:string"></xs:element>
                                                    <xs:element name="middle" type="xs:string" minOccurs="0"></xs:element>
                                                    <xs:element name="last" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="gender" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="phone" type="xs:string"></xs:element>
                                        <xs:element name="city" type="xs:string" minOccurs="0"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== bixash/Academics/dotWeb/dot-xml/dot-classwork/schema/phone/phoneNumbers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<phoneNumbers 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="phoneNumbers.xsd">
    <title>Phonebook</title>
    <entries>
        <entry>
            <name gender="female">
                <first>Kritika</first>
                <middle>Rajya laxmi</middle>
                <last>Shah</last>

            </name>

            <phone>+977 9860783944</phone>
            <city>Durbarsquare</city>

        </entry>
        <entry>
            <name>
                <first>moneey</first>
                <middle>Rajya laxmi</middle>
                <last></last>

            </name>

            <phone>29u98u298u2</phone>
            <city>eiiff</city>

        </entry>

    </entries>
</phoneNumbers>
